# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fib.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tfib.proto\"\x1b\n\nFibRequest\x12\r\n\x05order\x18\x01 \x01(\x03\"\x1c\n\x0b\x46ibResponse\x12\r\n\x05value\x18\x01 \x01(\x03\x32\x35\n\rFibCalculator\x12$\n\x07\x43ompute\x12\x0b.FibRequest\x1a\x0c.FibResponseb\x06proto3')



_FIBREQUEST = DESCRIPTOR.message_types_by_name['FibRequest']
_FIBRESPONSE = DESCRIPTOR.message_types_by_name['FibResponse']
FibRequest = _reflection.GeneratedProtocolMessageType('FibRequest', (_message.Message,), {
  'DESCRIPTOR' : _FIBREQUEST,
  '__module__' : 'fib_pb2'
  # @@protoc_insertion_point(class_scope:FibRequest)
  })
_sym_db.RegisterMessage(FibRequest)

FibResponse = _reflection.GeneratedProtocolMessageType('FibResponse', (_message.Message,), {
  'DESCRIPTOR' : _FIBRESPONSE,
  '__module__' : 'fib_pb2'
  # @@protoc_insertion_point(class_scope:FibResponse)
  })
_sym_db.RegisterMessage(FibResponse)

_FIBCALCULATOR = DESCRIPTOR.services_by_name['FibCalculator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIBREQUEST._serialized_start=13
  _FIBREQUEST._serialized_end=40
  _FIBRESPONSE._serialized_start=42
  _FIBRESPONSE._serialized_end=70
  _FIBCALCULATOR._serialized_start=72
  _FIBCALCULATOR._serialized_end=125
# @@protoc_insertion_point(module_scope)
